"""add_payment_created_at

Revision ID: 68001b9a8eda
Revises: 2a816e7c4e8a
Create Date: 2026-08-29 12:19:22.714935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68001b9a8eda'
down_revision: Union[str, Sequence[str], None] = '2a816e7c4e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'created_at')
    # ### end Alembic commands ###
