"""add_payment_intent_id

Revision ID: 89e83d58dcab
Revises: 68001b9a8eda
Create Date: 2026-09-01 15:03:27.230593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e83d58dcab'
down_revision: Union[str, Sequence[str], None] = '68001b9a8eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_intent_id', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'payments', ['payment_intent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'payment_intent_id')
    # ### end Alembic commands ###
